import {
  User,
  Workspace,
  Project,
  Task,
  Comment,
  ActivityLogItem,
  NotificationItem,
  FilterPreset,
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@workspace.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'owner',
    bio: 'Product Lead & Founder. Obsessed with snappy UI and developer productivity.',
    initials: 'AR',
  },
  {
    id: 'user-2',
    name: 'Sarah Chen',
    email: 'sarah.chen@workspace.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    bio: 'Senior Fullstack Engineer. React, TypeScript, and state management fan.',
    initials: 'SC',
  },
  {
    id: 'user-3',
    name: 'Marcus Brody',
    email: 'marcus.brody@workspace.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    bio: 'Product Designer. Crafting micro-interactions and accessible design systems.',
    initials: 'MB',
  },
  {
    id: 'user-4',
    name: 'Elena Rostova',
    email: 'elena.rostova@workspace.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'viewer',
    bio: 'Quality Assurance & Security Specialist. Read-only guest reviewer.',
    initials: 'ER',
  },
];

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-1',
    name: 'Acme Platform Eng',
    slug: 'acme-platform',
    icon: 'zap',
    color: '#6366f1',
    defaultView: 'kanban',
    members: [
      { userId: 'user-1', role: 'owner', joinedAt: '2026-01-10T08:00:00.000Z' },
      { userId: 'user-2', role: 'admin', joinedAt: '2026-01-15T09:30:00.000Z' },
      { userId: 'user-3', role: 'member', joinedAt: '2026-02-01T10:15:00.000Z' },
      { userId: 'user-4', role: 'viewer', joinedAt: '2026-02-10T14:20:00.000Z' },
    ],
    createdAt: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'ws-2',
    name: 'Design & Growth Studio',
    slug: 'design-studio',
    icon: 'palette',
    color: '#10b981',
    defaultView: 'list',
    members: [
      { userId: 'user-1', role: 'owner', joinedAt: '2026-01-20T10:00:00.000Z' },
      { userId: 'user-3', role: 'admin', joinedAt: '2026-01-22T11:00:00.000Z' },
      { userId: 'user-2', role: 'member', joinedAt: '2026-02-05T12:00:00.000Z' },
    ],
    createdAt: '2026-01-20T10:00:00.000Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    workspaceId: 'ws-1',
    name: 'Mobile App Launch v2.0',
    description: 'Cross-platform iOS and Android rollout for core offline-first workspace sync.',
    icon: 'rocket',
    color: '#6366f1',
    status: 'active',
    memberIds: ['user-1', 'user-2', 'user-3', 'user-4'],
    columns: [
      { id: 'todo', title: 'To Do', color: '#94a3b8' },
      { id: 'in_progress', title: 'In Progress', color: '#6366f1', wipLimit: 4 },
      { id: 'review', title: 'In Review', color: '#a855f7', wipLimit: 3 },
      { id: 'done', title: 'Completed', color: '#10b981' },
    ],
    defaultView: 'kanban',
    template: 'Sprint Board',
    createdAt: '2026-02-01T09:00:00.000Z',
    updatedAt: '2026-03-01T11:00:00.000Z',
  },
  {
    id: 'proj-2',
    workspaceId: 'ws-1',
    name: 'Design System 2.0',
    description: 'Component tokens, glassmorphic modals, dark theme contrast, and keyboard navigation.',
    icon: 'gem',
    color: '#ec4899',
    status: 'active',
    memberIds: ['user-1', 'user-2', 'user-3'],
    columns: [
      { id: 'todo', title: 'Backlog', color: '#94a3b8' },
      { id: 'in_progress', title: 'Designing', color: '#ec4899' },
      { id: 'review', title: 'Design Review', color: '#f59e0b' },
      { id: 'done', title: 'Shipped', color: '#10b981' },
    ],
    defaultView: 'list',
    template: 'Design Roadmap',
    createdAt: '2026-02-15T14:00:00.000Z',
    updatedAt: '2026-03-02T16:00:00.000Z',
  },
  {
    id: 'proj-3',
    workspaceId: 'ws-2',
    name: 'Growth & Onboarding Funnel',
    description: 'Self-serve workspace creation, interactive tour, and team invitation mechanics.',
    icon: 'trending-up',
    color: '#10b981',
    status: 'active',
    memberIds: ['user-1', 'user-3'],
    columns: [
      { id: 'todo', title: 'To Do', color: '#94a3b8' },
      { id: 'in_progress', title: 'In Flight', color: '#3b82f6' },
      { id: 'review', title: 'Validation', color: '#8b5cf6' },
      { id: 'done', title: 'Live in Prod', color: '#10b981' },
    ],
    defaultView: 'kanban',
    template: 'Growth Sprints',
    createdAt: '2026-02-20T10:00:00.000Z',
    updatedAt: '2026-03-03T18:00:00.000Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-101',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    title: 'Implement optimistic state update and rollback in Redux',
    description:
      'Ensure task movement across columns updates immediately in the UI and rolls back gracefully if simulated network fails.\n\n### Acceptance Criteria:\n- Dispatch optimistic action before async delay\n- Catch error and revert store state\n- Trigger notification toast with undo action',
    status: 'in_progress',
    priority: 'urgent',
    dueDate: '2026-03-10T18:00:00.000Z',
    assigneeId: 'user-2',
    tags: ['Frontend', 'Redux', 'Performance'],
    subtasks: [
      { id: 'sub-1', taskId: 'task-101', title: 'Create historySlice undo/redo stack', completed: true },
      { id: 'sub-2', taskId: 'task-101', title: 'Simulate 400ms network latency helper', completed: true },
      { id: 'sub-3', taskId: 'task-101', title: 'Add rollback reducer for failed mutations', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-02-28T10:00:00.000Z',
    updatedAt: '2026-03-04T12:00:00.000Z',
  },
  {
    id: 'task-102',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    title: 'Design accessible modal dialogs with light-dismiss',
    description:
      'Update task detail and workspace creation dialogs to support native light-dismiss (`closedby="any"` / backdrop click fallback) and focus trapping.',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-03-12T15:00:00.000Z',
    assigneeId: 'user-3',
    tags: ['Accessibility', 'UI', 'Dialog'],
    subtasks: [
      { id: 'sub-4', taskId: 'task-102', title: 'Implement backdrop blur and dark mode styles', completed: true },
      { id: 'sub-5', taskId: 'task-102', title: 'Verify ESC key closes active dialog', completed: true },
      { id: 'sub-6', taskId: 'task-102', title: 'Check outside click bounding rectangle', completed: true },
    ],
    attachments: [],
    order: 1,
    createdAt: '2026-03-01T09:30:00.000Z',
    updatedAt: '2026-03-04T14:30:00.000Z',
  },
  {
    id: 'task-103',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    title: 'Setup IndexedDB persistent database & JSON export/import',
    description:
      'Store complete application state into IndexedDB for offline reliability. Implement schema validator for JSON backups.',
    status: 'review',
    priority: 'high',
    dueDate: '2026-03-08T20:00:00.000Z',
    assigneeId: 'user-2',
    tags: ['Offline', 'IndexedDB', 'Data'],
    subtasks: [
      { id: 'sub-7', taskId: 'task-103', title: 'Build IndexedDB wrapper class', completed: true },
      { id: 'sub-8', taskId: 'task-103', title: 'Export JSON file generation', completed: true },
      { id: 'sub-9', taskId: 'task-103', title: 'Import file validation error checks', completed: true },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-02-25T11:00:00.000Z',
    updatedAt: '2026-03-05T09:00:00.000Z',
  },
  {
    id: 'task-104',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    title: 'Command Palette (Cmd+K) quick navigation',
    description:
      'Add global Cmd+K listener to trigger spotlight search across workspaces, projects, tasks, and theme toggling.',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-03-15T18:00:00.000Z',
    assigneeId: 'user-1',
    tags: ['Keyboard', 'Productivity'],
    subtasks: [
      { id: 'sub-10', taskId: 'task-104', title: 'Hook up global keyboard shortcut Cmd+K / Ctrl+K', completed: false },
      { id: 'sub-11', taskId: 'task-104', title: 'Filter search results with fuzzy matching', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-03-02T13:00:00.000Z',
    updatedAt: '2026-03-02T13:00:00.000Z',
  },
  {
    id: 'task-105',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    title: 'Role-based permission gating for Viewers',
    description:
      'Simulate Elena (Viewer role) logging in. Ensure edit buttons, deletion triggers, and task creation show tooltips and disabled states.',
    status: 'done',
    priority: 'high',
    dueDate: '2026-03-05T12:00:00.000Z',
    assigneeId: 'user-4',
    tags: ['Security', 'Roles', 'QA'],
    subtasks: [
      { id: 'sub-12', taskId: 'task-105', title: 'Write usePermissions hook with role matrix', completed: true },
      { id: 'sub-13', taskId: 'task-105', title: 'Render Access Denied banner when required', completed: true },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-02-20T10:00:00.000Z',
    updatedAt: '2026-03-04T18:00:00.000Z',
  },
  {
    id: 'task-106',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    title: 'Simulate background collaborator activity via mock socket',
    description:
      'Run fake socket events every 45 seconds to add comments, move tasks, or trigger toast alerts so the workspace feels alive.',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-03-18T18:00:00.000Z',
    assigneeId: 'user-1',
    tags: ['Realtime', 'Simulation'],
    subtasks: [],
    attachments: [],
    order: 1,
    createdAt: '2026-03-03T15:00:00.000Z',
    updatedAt: '2026-03-03T15:00:00.000Z',
  },
  {
    id: 'task-201',
    workspaceId: 'ws-1',
    projectId: 'proj-2',
    title: 'Design token audit: Slate palette & custom glassmorphism',
    description:
      'Standardize background variables, card border highlights, and dark mode contrast ratios across all components.',
    status: 'done',
    priority: 'high',
    dueDate: '2026-03-04T12:00:00.000Z',
    assigneeId: 'user-3',
    tags: ['Design', 'Tokens', 'CSS'],
    subtasks: [
      { id: 'sub-14', taskId: 'task-201', title: 'Export CSS custom properties in globals.css', completed: true },
      { id: 'sub-15', taskId: 'task-201', title: 'Test dark theme readability', completed: true },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-02-22T09:00:00.000Z',
    updatedAt: '2026-03-04T11:00:00.000Z',
  },
  {
    id: 'task-202',
    workspaceId: 'ws-1',
    projectId: 'proj-2',
    title: 'Calendar view monthly task scheduling',
    description:
      'Build monthly grid calendar view with task due date chips, quick day task creation, and month navigation.',
    status: 'in_progress',
    priority: 'medium',
    dueDate: '2026-03-14T18:00:00.000Z',
    assigneeId: 'user-2',
    tags: ['Calendar', 'Views'],
    subtasks: [
      { id: 'sub-16', taskId: 'task-202', title: 'Monthly grid date calculation helper', completed: true },
      { id: 'sub-17', taskId: 'task-202', title: 'Render task pills with priority colors', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-02-26T14:00:00.000Z',
    updatedAt: '2026-03-05T08:00:00.000Z',
  },
  {
    id: 'task-203',
    workspaceId: 'ws-1',
    projectId: 'proj-2',
    title: 'Interactive @mention autocomplete in comment threads',
    description:
      'When typing `@` in task comment editor, show dropdown of workspace team members and insert tag.',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-03-16T17:00:00.000Z',
    assigneeId: 'user-3',
    tags: ['Comments', 'Collaboration'],
    subtasks: [],
    attachments: [],
    order: 0,
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'task-301',
    workspaceId: 'ws-2',
    projectId: 'proj-3',
    title: 'Self-serve workspace onboarding flow',
    description:
      'Allow new team members to pick predefined project templates (Sprint Board, Bug Tracker, Roadmap).',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-03-11T12:00:00.000Z',
    assigneeId: 'user-1',
    tags: ['Growth', 'Onboarding'],
    subtasks: [
      { id: 'sub-18', taskId: 'task-301', title: 'Define template configurations', completed: true },
      { id: 'sub-19', taskId: 'task-301', title: 'Generate sample tasks on template selection', completed: false },
    ],
    attachments: [],
    order: 0,
    createdAt: '2026-02-28T16:00:00.000Z',
    updatedAt: '2026-03-05T10:00:00.000Z',
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'comm-1',
    taskId: 'task-101',
    userId: 'user-2',
    content: 'The optimistic update reducer is wired! Pushing the 400ms artificial latency now.',
    createdAt: '2026-03-04T12:30:00.000Z',
  },
  {
    id: 'comm-2',
    taskId: 'task-101',
    userId: 'user-1',
    content: 'Awesome job @Sarah Chen. Make sure the toast includes a clickable "Undo" button.',
    createdAt: '2026-03-04T13:15:00.000Z',
  },
  {
    id: 'comm-3',
    taskId: 'task-102',
    userId: 'user-3',
    content: 'Verified light dismiss on Chrome 134! Adding bounding box check fallback for older engines.',
    createdAt: '2026-03-04T15:00:00.000Z',
  },
];

export const INITIAL_ACTIVITY: ActivityLogItem[] = [
  {
    id: 'act-1',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    taskId: 'task-101',
    taskTitle: 'Implement optimistic state update and rollback in Redux',
    userId: 'user-2',
    action: 'updated_status',
    details: 'Moved task from To Do to In Progress',
    timestamp: '2026-03-04T12:00:00.000Z',
  },
  {
    id: 'act-2',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    taskId: 'task-102',
    taskTitle: 'Design accessible modal dialogs with light-dismiss',
    userId: 'user-3',
    action: 'assigned_task',
    details: 'Assigned task to Marcus Brody',
    timestamp: '2026-03-04T14:30:00.000Z',
  },
  {
    id: 'act-3',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    taskId: 'task-105',
    taskTitle: 'Role-based permission gating for Viewers',
    userId: 'user-4',
    action: 'completed_task',
    details: 'Marked task as completed',
    timestamp: '2026-03-04T18:00:00.000Z',
  },
  {
    id: 'act-4',
    workspaceId: 'ws-1',
    projectId: 'proj-1',
    taskId: 'task-103',
    taskTitle: 'Setup IndexedDB persistent database & JSON export/import',
    userId: 'user-2',
    action: 'updated_status',
    details: 'Moved task to In Review',
    timestamp: '2026-03-05T09:00:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'mentioned',
    title: 'Mentioned in a comment',
    message: 'Sarah Chen mentioned you on "Implement optimistic state update and rollback in Redux"',
    taskId: 'task-101',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    read: false,
    createdAt: '2026-03-04T13:15:00.000Z',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'assigned',
    title: 'New task assigned',
    message: 'You were assigned to "Command Palette (Cmd+K) quick navigation"',
    taskId: 'task-104',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    read: false,
    createdAt: '2026-03-02T13:00:00.000Z',
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'due_soon',
    title: 'Task due soon',
    message: '"Setup IndexedDB persistent database & JSON export/import" is due on Mar 8',
    taskId: 'task-103',
    projectId: 'proj-1',
    workspaceId: 'ws-1',
    read: true,
    createdAt: '2026-03-05T07:00:00.000Z',
  },
];

export const DEFAULT_FILTER_PRESETS: FilterPreset[] = [
  {
    id: 'preset-all',
    name: 'All Tasks',
    icon: 'ListFilter',
    isCustom: false,
    filters: {
      search: '',
      assigneeId: null,
      status: [],
      priority: [],
      tags: [],
      dueDateRange: 'all',
    },
  },
  {
    id: 'preset-my-tasks',
    name: 'My Tasks',
    icon: 'User',
    isCustom: false,
    filters: {
      search: '',
      status: [],
      priority: [],
      tags: [],
      dueDateRange: 'all',
    },
  },
  {
    id: 'preset-urgent',
    name: 'Urgent & High Priority',
    icon: 'Flame',
    isCustom: false,
    filters: {
      search: '',
      assigneeId: null,
      status: [],
      priority: ['urgent', 'high'],
      tags: [],
      dueDateRange: 'all',
    },
  },
  {
    id: 'preset-due-soon',
    name: 'Due This Week',
    icon: 'Clock',
    isCustom: false,
    filters: {
      search: '',
      assigneeId: null,
      status: [],
      priority: [],
      tags: [],
      dueDateRange: 'this_week',
    },
  },
];

export const PROJECT_TEMPLATES = [
  {
    id: 'sprint-board',
    name: 'Sprint Board',
    description: 'Classic Scrum sprint setup with Todo, In Progress, Review, and Done.',
    icon: 'list-todo',
    color: '#6366f1',
    columns: [
      { id: 'todo', title: 'To Do', color: '#94a3b8' },
      { id: 'in_progress', title: 'In Progress', color: '#6366f1', wipLimit: 5 },
      { id: 'review', title: 'Code Review', color: '#a855f7', wipLimit: 3 },
      { id: 'done', title: 'Done', color: '#10b981' },
    ],
    defaultView: 'kanban' as const,
  },
  {
    id: 'bug-tracker',
    name: 'Bug Tracker',
    description: 'Issue triage, repro validation, patch in progress, and verified resolved.',
    icon: 'bug',
    color: '#f43f5e',
    columns: [
      { id: 'triage', title: 'Triage / Reported', color: '#f43f5e' },
      { id: 'investigating', title: 'Investigating', color: '#f59e0b' },
      { id: 'fixing', title: 'Fix in Review', color: '#3b82f6' },
      { id: 'verified', title: 'Verified / Closed', color: '#10b981' },
    ],
    defaultView: 'list' as const,
  },
  {
    id: 'product-roadmap',
    name: 'Product Roadmap',
    description: 'High-level initiatives grouped by Quarter and Status with calendar tracking.',
    icon: 'compass',
    color: '#8b5cf6',
    columns: [
      { id: 'q1_backlog', title: 'Backlog / Ideas', color: '#94a3b8' },
      { id: 'q2_active', title: 'Now / Building', color: '#8b5cf6' },
      { id: 'q3_next', title: 'Next Up', color: '#06b6d4' },
      { id: 'shipped', title: 'Shipped', color: '#10b981' },
    ],
    defaultView: 'calendar' as const,
  },
];
